version: '3'

services:
  caddy:
    restart: always
    image: abiosoft/caddy
    container_name: caddy
    ports:
      - 80:80
    command: -agree=true -http2 -conf /etc/Caddyfile # -log stdout -errors stdout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/caddy/Caddyfile:/etc/Caddyfile
      - /app/caddy/html:/opt/html
      - /data/caddy/data:/root/.caddy
      - /data/caddy/logs:/opt/logs

  portainer:
    restart: always
    image: portainer/portainer
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer:/data

  mongo:
    restart: always
    container_name: mongo
    image: bitnami/mongodb:latest
    ports:
      - 27017:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
    volumes:
      - /data/db-mongo:/data/db 

  mongo-rs1:
    restart: always
    container_name: mongo-rs1
    image: bitnami/mongodb:latest
    depends_on:
      - mongo
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongo
      - MONGODB_PRIMARY_PORT_NUMBER=27017

  mongo-rs2:
    restart: always
    container_name: mongo-rs2
    image: bitnami/mongodb:latest
    depends_on:
      - mongo
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongo
      - MONGODB_PRIMARY_PORT_NUMBER=27017
