module.exports = [
  { segment: 'birthday-bot', field: 'proxy', created: new Date(), value: 'http://s-thcw-posweb01.pos.cmg.co.th:3000' },
  { segment: 'birthday-bot', field: 'endpoint', created: new Date(), value: 'http://s-thcw-posdb95.pos.cmg.co.th/api' },
  { segment: 'birthday-bot', field: 'crontab', created: new Date(), value: '0 8 * * *' },
  { segment: 'birthday-bot', field: 'botname', created: new Date(), value: 'gamgoum' },
  { segment: 'birthday-bot', field: 'line', created: new Date(), value: 'U23d0cfb62986804cbacdf63398aef4cf' },
  { segment: 'birthday-bot', field: 'color', created: new Date(), value: [
    '#eccc68',
    '#ff7f50',
    '#ff6b81',
    '#f3a683',
    '#57606f',
    '#ffa502',
    '#ff4757',
    '#747d8c',
    '#2f3542',
    '#7bed9f',
    '#70a1ff',
    '#5352ed',
    '#2ed573',
    '#1e90ff',
    '#3742fa',
    '#f7d794',
    '#778beb',
    '#e77f67',
    '#cf6a87',
    '#c44569',
    '#e15f41',
    '#546de5',
    '#f5cd79',
    '#f19066',
    '#786fa6',
    '#f8a5c2',
    '#ea8685',
    '#e66767',
    '#3dc1d3',
    '#574b90'
  ] },
  { segment: 'birthday-bot', field: 'icon', created: new Date(), value: [ '🎉','🎊','🎈' ] },
  { segment: 'birthday-bot', field: 'happyday', created: new Date(), value: [
    { greeting: 'Wishing you many happy returns on your birthday.', by: 'Nuengruethai Eamsumang' },
    { greeting: 'Happy birth day; I wish you always be healthy happy in your life and achieve all your goal.', by: 'Nuengruethai Eamsumang' },
    { greeting: 'Hip, hip, hooray! It’s your birthday today!', by: 'Nuengruethai Eamsumang' },
    { greeting: 'Happy birth day for you and God blessing you and your family hopeful and fun all the year.', by: 'Nuengruethai Eamsumang' },
  ] }
]

