Vagrant.configure("2") do |config|
  config.vm.box = "hbsmith/awslinux"
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.synced_folder "../", "/app/devops-ui"
  config.vm.synced_folder "C:/Users/ThKanane/Downloads/gitlab-ce", "/gitlab-ce"
  
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    vb.memory = "2048"
  end
  config.vm.provision "shell", inline: <<-SHELL
    yum update -y
  SHELL
end
