version: '3'

# // commandline for apply streaming data.
# docker exec -it mongo-pr mongo
# db.enableFreeMonitoring()
# rs.slaveOk()

services:
  mongo-pr:
    restart: always
    container_name: mongo-pr
    image: bitnami/mongodb:latest
    ports:
      - 27017:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
    volumes:
      - /data/db-mongo:/data/db 

  mongo-sc:
    restart: always
    container_name: mongo-sc
    image: bitnami/mongodb:latest
    depends_on:
      - mongo-pr
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongo-pr
      - MONGODB_PRIMARY_PORT_NUMBER=27017

  mongo-ab:
    restart: always
    container_name: mongo-ab
    image: bitnami/mongodb:latest
    depends_on:
      - mongo-pr
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongo-pr
      - MONGODB_PRIMARY_PORT_NUMBER=27017
